---

- name: Install zookeeper
  include_role:
    name: zookeeper

- name: Install kafka
  include: build.yml
  tags:
    - build

- name: Install kafka
  include: configure.yml
  tags:
    - configure
